### ISSUE TITLE
H2 Database?

### ISSUE THREAD

**Issue by Vinicius-CoutinhoR** [RaphaelSilv4/MTE#1]
Vocês têm certeza de utilizar o banco de dados H2? Porque não utilizam o postgres ou o MySQL? Inclusive tem no meu projeto o pom.xml com as dependencias e o application.yaml para rodar com o MySQL. 

Já iria poupar um bom tempo de vocês com o projeto.

**Comment by fransilva0** [comment]
@TharcioCBM estava pensando em mudar para Postgres juntamente com @lucasdelimagarreto pelo que eu sei, tá em progresso a análise dessa possibilidade.
